import type { Config } from 'tailwindcss'

/**
 * Fratello Design System — Tailwind theme.
 * Every value maps to a token in app/design-tokens.css / fratello-DS.json.
 * Components must use these utilities (or the CSS vars directly) — never
 * arbitrary hex/px values. See DESIGN_SYSTEM.md.
 */
const config: Config = {
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        neutral: {
          0: 'var(--color-neutral-0)',
          25: 'var(--color-neutral-25)',
          50: 'var(--color-neutral-50)',
          100: 'var(--color-neutral-100)',
          200: 'var(--color-neutral-200)',
          300: 'var(--color-neutral-300)',
          400: 'var(--color-neutral-400)',
          500: 'var(--color-neutral-500)',
          600: 'var(--color-neutral-600)',
          700: 'var(--color-neutral-700)',
          800: 'var(--color-neutral-800)',
          900: 'var(--color-neutral-900)',
          950: 'var(--color-neutral-950)',
        },
        brand: {
          10: 'var(--color-brand-10)',
          25: 'var(--color-brand-25)',
          50: 'var(--color-brand-50)',
          100: 'var(--color-brand-100)',
          200: 'var(--color-brand-200)',
          300: 'var(--color-brand-300)',
          400: 'var(--color-brand-400)',
          500: 'var(--color-brand-500)',
          600: 'var(--color-brand-600)',
          700: 'var(--color-brand-700)',
          800: 'var(--color-brand-800)',
          900: 'var(--color-brand-900)',
        },
        error: {
          50: 'var(--color-error-50)',
          100: 'var(--color-error-100)',
          200: 'var(--color-error-200)',
          300: 'var(--color-error-300)',
          400: 'var(--color-error-400)',
          500: 'var(--color-error-500)',
          600: 'var(--color-error-600)',
          700: 'var(--color-error-700)',
          800: 'var(--color-error-800)',
          900: 'var(--color-error-900)',
        },
        warning: {
          50: 'var(--color-warning-50)',
          100: 'var(--color-warning-100)',
          200: 'var(--color-warning-200)',
          300: 'var(--color-warning-300)',
          400: 'var(--color-warning-400)',
          500: 'var(--color-warning-500)',
          600: 'var(--color-warning-600)',
          700: 'var(--color-warning-700)',
          800: 'var(--color-warning-800)',
          900: 'var(--color-warning-900)',
        },
        pastel: { 25: 'var(--color-pastel-25)' },
        // semantic display fills (chips, badges, avatars)
        display: {
          neutral: 'var(--display-neutral)',
          brand: 'var(--display-brand)',
          error: 'var(--display-error)',
          warning: 'var(--display-warning)',
        },
        // semantic icon colors (use as text-* / fill-* / stroke-*)
        icon: {
          'white-remain': 'var(--icon-white-remain)',
          'light-gray': 'var(--icon-light-gray)',
          'dark-gray': 'var(--icon-dark-gray)',
          error: 'var(--icon-error)',
          warning: 'var(--icon-warning)',
          'black-remain': 'var(--icon-black-remain)',
          brand: 'var(--icon-brand)',
          disabled: 'var(--icon-disabled)',
          'black-invert': 'var(--icon-black-invert)',
          'white-invert': 'var(--icon-white-invert)',
        },
        // semantic button fills
        btn: {
          primary: 'var(--btn-primary)',
          'primary-pressed': 'var(--btn-primary-pressed)',
          'primary-light': 'var(--btn-primary-light)',
          neutral: 'var(--btn-neutral)',
          'neutral-pressed': 'var(--btn-neutral-pressed)',
          disabled: 'var(--btn-disabled)',
          error: 'var(--btn-error)',
          'error-pressed': 'var(--btn-error-pressed)',
          'error-light': 'var(--btn-error-light)',
          'ghost-pressed': 'var(--btn-ghost-pressed)',
        },
      },
      textColor: {
        primary: 'var(--text-primary)',
        secondary: 'var(--text-secondary)',
        tertiary: 'var(--text-tertiary)',
        disabled: 'var(--text-disabled)',
        'error-token': 'var(--text-error)',
        'warning-token': 'var(--text-warning)',
        'brand-token': 'var(--text-brand)',
        'white-remain': 'var(--text-white-remain)',
        'primary-invert': 'var(--text-primary-invert)',
        'primary-remain': 'var(--text-primary-remain)',
        'secondary-invert': 'var(--text-secondary-invert)',
        'secondary-remain': 'var(--text-secondary-remain)',
      },
      backgroundColor: {
        primary: 'var(--bg-primary)',
        secondary: 'var(--bg-secondary)',
        tertiary: 'var(--bg-tertiary)',
        card: 'var(--bg-card)',
        nav: 'var(--bg-nav)',
        field: 'var(--bg-field)',
        column: 'var(--bg-column)',
        overlay: 'var(--bg-overlay)',
        'primary-remain': 'var(--bg-primary-remain)',
        'brand-pastel': 'var(--bg-brand-pastel)',
        'brand-green': 'var(--bg-brand-green)',
      },
      borderColor: {
        'neutral-primary': 'var(--border-neutral-primary)',
        'neutral-secondary': 'var(--border-neutral-secondary)',
        'neutral-tertiary': 'var(--border-neutral-tertiary)',
        'error-token': 'var(--border-error)',
        'warning-token': 'var(--border-warning)',
        'brand-token': 'var(--border-brand)',
        white: 'var(--border-white)',
        disabled: 'var(--border-disabled)',
        'neutral-primary-invert': 'var(--border-neutral-primary-invert)',
      },
      fontFamily: {
        sans: ['var(--font-figtree)', 'Figtree', 'system-ui', 'sans-serif'],
        // Brand wordmark only (Fratello serif lockup) — not for UI text.
        serif: ['var(--font-lora)', 'Lora', 'Georgia', 'serif'],
      },
      // text tokens: [size, { lineHeight, letterSpacing }] — weight applied separately
      fontSize: {
        h1: ['48px', { lineHeight: '57.6px', letterSpacing: '-2px' }],
        h2: ['36px', { lineHeight: '43.2px', letterSpacing: '-2px' }],
        h3: ['28px', { lineHeight: '33.6px' }],
        h4: ['24px', { lineHeight: '28.8px' }],
        h5: ['20px', { lineHeight: '24px' }],
        h6: ['18px', { lineHeight: '21.6px' }],
        'action-big': ['18px', { lineHeight: '24px' }],
        'action-medium': ['16px', { lineHeight: '20px' }],
        'action-small': ['14px', { lineHeight: '16px' }],
        'paragraph-big': ['16px', { lineHeight: '24px' }],
        'paragraph-medium': ['14px', { lineHeight: '20px' }],
        'paragraph-small': ['12px', { lineHeight: '16px' }],
        'paragraph-xs': ['11px', { lineHeight: '16px' }],
        'label-big': ['16px', { lineHeight: '24px' }],
        'label-medium': ['14px', { lineHeight: '20px' }],
        'label-small': ['12px', { lineHeight: '16px' }],
        'field-label': ['14px', { lineHeight: '14px' }],
        'field-input': ['16px', { lineHeight: '20px' }],
        'field-caption': ['12px', { lineHeight: '14px' }],
      },
      borderRadius: {
        // DS radius tokens; tailwind defaults rounded(4) lg(8) xl(12) 2xl(16) 3xl(24) already align
        'token-4': '4px',
        'token-8': '8px',
        'token-12': '12px',
        'token-16': '16px',
        'token-24': '24px',
        'token-40': '40px',
        circle: '400px',
      },
      boxShadow: {
        'center-sm': 'var(--shadow-center-sm)',
        'center-md': 'var(--shadow-center-md)',
        'center-lg': 'var(--shadow-center-lg)',
        'regular-sm': 'var(--shadow-regular-sm)',
        'regular-md': 'var(--shadow-regular-md)',
        'regular-lg': 'var(--shadow-regular-lg)',
        'regular-xl': 'var(--shadow-regular-xl)',
      },
      transitionTimingFunction: {
        standard: 'cubic-bezier(0.5, 0, 0.2, 1)',
        exit: 'cubic-bezier(0.4, 1, 0.2, 1)',
      },
      transitionDuration: {
        '400': '400ms',
      },
    },
  },
  plugins: [],
}

export default config
